apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gic3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: registry.deti:5000/webgic3
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: username 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: password
          - name: POSTGRES_HOST
            value: postgres-svc
          - name: REDIS_LOCATION
            value: redis
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-redis-secret
                key: password   
        ports:
          - name: web
            containerPort: 80
          - name: uwsgi
            containerPort: 9000
        volumeMounts:
          - mountPath: /home/mediacms.io/mediacms/static
            name: staticfiles
          - mountPath: /home/mediacms.io/mediacms/media_files
            name: mediafiles
  
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfilespvc
        - name: mediafiles
          persistentVolumeClaim:
              claimName: mediafilespvc 

# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: gic3
spec:
  ports:
  - name: uwsgi
    port: 9000
    targetPort: 9000
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: api




