apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworkershort
  namespace: gic3
spec:
  selector:
    matchLabels:
      app: celeryworkershort
  template:
    metadata:
      labels:
        app: celeryworkershort
    spec:
      containers:
      - name: celeryworkerlong
        image: registry.deti:5000/celeryworkershortgic3
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: username 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: password
          - name: POSTGRES_HOST
            value: postgres-svc
          - name: REDIS_LOCATION
            value: redis      
        volumeMounts:
        - mountPath: /home/mediacms.io/mediacms/media_files
          name: mediafiles
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: web  
      volumes:
        - name: mediafiles
          persistentVolumeClaim:
              claimName: mediafilespvc    
