apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworkerlong
  namespace: gic3
spec:
  selector:
    matchLabels:
      app: celeryworkerlong
  template:
    metadata:
      labels:
        app: celeryworkerlong
    spec:
      containers:
      - name: celeryworker
        image: registry.deti:5000/celeryworkerlonggic3
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: username 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: password
          - name: POSTGRES_HOST
            value: postgres-svc
          - name: REDIS_LOCATION
            value: redis  
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-redis-secret
                key: password      
        volumeMounts:
        - mountPath: /home/mediacms.io/mediacms/media_files
          name: mediafiles
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web
                - api


      volumes:
        - name: mediafiles
          persistentVolumeClaim:
              claimName: mediafilespvc    
