apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
  namespace: gic3
data:
  config.hcl: |
    listen {
      port = 4040
    }

    namespace "gic3" {
      source = {
        syslog {
          listen_address = "udp://127.0.0.1:5531"
          format = "auto"
          tags = [
            "nginx"
          ]
        }
       
      }


      format = "$remote_addr - - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
      relabel "remote_addr" { from = "remote_addr" }

      relabel "request" { from = "request" }

      labels {
        app = "nginx"
      }
    }