# NGINX Config map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: gic3
  labels:
    app-name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 10240;
    }

    worker_rlimit_nofile 20000; #each connection needs a filehandle (or 2 if you are proxying)
    http {
        proxy_connect_timeout 75;
        proxy_read_timeout 12000;
        client_max_body_size 5800M;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 10;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

        log_format syslog_format '$remote_addr - - [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent"';

        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        server {
            listen 80;
            listen [::]:80;
            server_name localhost;

            gzip on;
            #access_log /var/log/nginx/mediacms.io.access.log;
            access_log syslog:server=127.0.0.1:5531,facility=local7,tag=nginx,severity=info;
            error_log /var/log/nginx/mediacms.io.error.log warn;

            location /static {
                alias /home/mediacms.io/mediacms/static;
            }

            # location /media/original {
            #     alias /var/www/media/original;
            # }

            location /media {
                alias /home/mediacms.io/mediacms/media_files;
            }
            location /demo {
                root /home/mediacms.io/mediacms/static/ ;
                index index.html;
            }

            location /nginx_status {
                allow all;
                access_log on;
                stub_status on;
            }
            
            location /metrics {
                allow all;
                access_log on;
                stub_status on;
            }

            location / {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

                uwsgi_param  QUERY_STRING       $query_string;
                uwsgi_param  REQUEST_METHOD     $request_method;
                uwsgi_param  CONTENT_TYPE       $content_type;
                uwsgi_param  CONTENT_LENGTH     $content_length;

                uwsgi_param  REQUEST_URI        $request_uri;
                uwsgi_param  PATH_INFO          $document_uri;
                uwsgi_param  DOCUMENT_ROOT      $document_root;
                uwsgi_param  SERVER_PROTOCOL    $server_protocol;
                uwsgi_param  REQUEST_SCHEME     $scheme;
                uwsgi_param  HTTPS              $https if_not_empty;

                uwsgi_param  REMOTE_ADDR        $remote_addr;
                uwsgi_param  REMOTE_PORT        $remote_port;
                uwsgi_param  SERVER_PORT        $server_port;
                uwsgi_param  SERVER_NAME        $server_name;

                uwsgi_pass web-svc:9000;
            }

            location /api {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

                uwsgi_param  QUERY_STRING       $query_string;
                uwsgi_param  REQUEST_METHOD     $request_method;
                uwsgi_param  CONTENT_TYPE       $content_type;
                uwsgi_param  CONTENT_LENGTH     $content_length;

                uwsgi_param  REQUEST_URI        $request_uri;
                uwsgi_param  PATH_INFO          $document_uri;
                uwsgi_param  DOCUMENT_ROOT      $document_root;
                uwsgi_param  SERVER_PROTOCOL    $server_protocol;
                uwsgi_param  REQUEST_SCHEME     $scheme;
                uwsgi_param  HTTPS              $https if_not_empty;

                uwsgi_param  REMOTE_ADDR        $remote_addr;
                uwsgi_param  REMOTE_PORT        $remote_port;
                uwsgi_param  SERVER_PORT        $server_port;
                uwsgi_param  SERVER_NAME        $server_name;

                uwsgi_pass api-svc:9000;
            }
        }
    }



    