apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfilespvc
  namespace: gic3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediafilespvc
  namespace: gic3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gic3
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4040"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: registry.deti:5000/nginxgic3
          name: nginx
          ports:
            - name: nginx
              containerPort: 80
          resources: {}
          volumeMounts:
            - name: staticfiles
              mountPath: /home/mediacms.io/mediacms/static
            - name: mediafiles
              mountPath: /home/mediacms.io/mediacms/media_files
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
        # - image: nginx/nginx-prometheus-exporter:0.10.0
        #   name: exporter
        #   ports:
        #     - name: exporter
        #       containerPort: 9113
        #   args:
        #     - "-nginx.scrape-uri=http://localhost/nginx_status"
        - image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
          name: exporter
          args: ["-config-file", "/etc/prometheus-nginxlog-exporter/config.hcl"]
          volumeMounts:
            - name: exporter-config
              mountPath: /etc/prometheus-nginxlog-exporter

      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: exporter-config
          configMap:
            name: exporter-config
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfilespvc
        - name: mediafiles
          persistentVolumeClaim:
              claimName: mediafilespvc 


# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: gic3
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  - name: exporter
    port: 4040
    targetPort: 4040
  selector:
    app: nginx
