apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus-config
  namespace: gic3
data:
  prometheus.rules: |-
    groups:
    # - name: Max Virtual Memory
    #   rules:
    #   - alert: Process virtual memory exceeded
    #     expr: sum(process_virtual_memory_bytes) > 10^12
    #     for: 1m
    #     labels:
    #       severity: High
    #     annotations:
    #       summary: Service Down
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 20s      # time between each scrape (data pull from exporters), can be overrided in specific jobs
      evaluation_interval: 20s  # time between each evaluation of Prometheus' alerting rules
      # external_labels:
      #   monitor: 'gic3-monitor'
    rule_files:
      - /etc/prometheus/prometheus.rules
    # alerting:
    #   ...

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    
    - job_name: 'kubernetes-nodes'
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
    
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          regex: metrics
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: job