files_uploaded:
  values:
    - "file_count"
  query: "SELECT COUNT(*) AS file_count FROM files_media;"
  master: true

max_video_likes:
  values:
    - "max_likes"
  query: "SELECT MAX(likes) FROM files_media;"
  master: true

max_video_dislikes:
  values:
    - "max_dislikes"
  query: "SELECT MAX(dislikes) FROM files_media;"
  master: true

max_video_views:
  values:
    - "max_views"
  query: "SELECT MAX(views) FROM files_media;"
  master: true

failed_videos_encoding:
  values:
    - "fail_encodes_count"
  query: "SELECT COUNT(*) FROM files_media WHERE encoding_status = 'fail';"
  master: true

