FROM alpine

RUN apk add postgresql && \ 
    mkdir /run/postgresql && \
    chown postgres:postgres /run/postgresql/
USER postgres

RUN mkdir /var/lib/postgresql/data && \
    chmod 0700 /var/lib/postgresql/data && \ 
    initdb -D /var/lib/postgresql/data && \
    pg_ctl start -D /var/lib/postgresql/data