FROM nginx:1.20-alpine

# Setting up internal nginx server
# HTTPS setup is delegated to a reverse proxy running infront of the application
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx_http_only.conf  /etc/nginx/sites-available/default.conf
COPY ./nginx_http_only.conf  /etc/nginx/sites-enabled/default
COPY ./uwsgi_params  /etc/nginx/sites-enabled/uwsgi_params
COPY ./nginx.conf  /etc/nginx/nginx.conf
