FROM redis

VOLUME ["/data"]

USER redis
# Expose the ports for redis
EXPOSE 6379
# Start Redis Server
#Redis on Docker cannot be ran on background by default, you have to use the -d flag
CMD ["redis-server"]