version: "3.8"
services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 80:80
        volumes:
            - ./mediacmsfiles/static:/var/www/static
    db:
        build: 
            context: .
            dockerfile: Dockerfile.postgres
        restart: always
    redis:
        build: 
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - 6379:6379
        restart: always
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        deploy:
            replicas: 1
        environment:
            ENABLE_UWSGI: 'yes'
            ADMIN_USER: 'admin'
            ADMIN_EMAIL: 'admin@localhost'
        ports:
            - 9000:9000
        volumes:
            - ./:/home/mediacms.io/mediacms/
        depends_on:
            - redis
            - db
    celery_beat:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            ENABLE_CELERY_BEAT: 'yes'
        volumes:
            - ./:/home/mediacms.io/mediacms/
        depends_on:
            - redis
        restart: always
    celery_worker:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            ENABLE_CELERY_WORKER: 'yes'
        deploy:
            replicas: 1
        volumes:
            - ./:/home/mediacms.io/mediacms/
        depends_on:
            - web
        restart: always
volumes:
    www:

