version: "3.8"
services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 80:80
        volumes:
            - ./mediacmsfiles/static:/var/www/static
    db:
        build: 
            context: .
            dockerfile: Dockerfile.postgres
        restart: always
    redis:
        build: 
            context: .
            dockerfile: Dockerfile.redis
        ports:
            - 6379:6379
        restart: always
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        deploy:
            replicas: 1
        ports:
            - 9000:9000
        volumes:
            - ./:/home/mediacms.io/mediacms/
        environment:
            ADMIN_USER: 'admin'
            ADMIN_EMAIL: 'admin@localhost'
        depends_on:
            - redis
            - db
    celery_beat:
        build: 
            context: .
            dockerfile: Dockerfile
        command: celery -A cms beat -l info
        # command: celery -A files beat -l info
        volumes:
            - ./:/home/mediacms.io/mediacms/
        depends_on:
            - redis
    celery_worker:
        build: 
            context: .
            dockerfile: Dockerfile
        command: celery -A cms worker -l info
        # command: celery -A files worker -l info
        deploy:
            replicas: 1
        volumes:
            - ./:/home/mediacms.io/mediacms/
        depends_on:
            - web
            - redis
volumes:
    www:

