global:
  scrape_interval: 20s      # time between each scrape (data pull from exporters), can be overrided in specific jobs
  evaluation_interval: 20s  # time between each evaluation of Prometheus' alerting rules
  # external_labels:
  #   monitor: 'gic3-monitor'
rule_files:
  - prometheus.rules
# alerting:
#   ...

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'kubernetes-nodes'
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: hostname
    replacement: /api/v1/nodes/${1}/proxy/metrics

- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      regex: metrics
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_name]
      target_label: hostname
      replacement: __host__
